import asyncio
import sys
import pprint

from utils import get_client, get_config_dir

"""
Get the transformer tap settings generated by a calibration run.

Use the ID/name you provided in run_calibration.py
"""

CALIBRATION_ID = "test"  # ID of run to fetch calibration sets for


async def print_loop(argv):
    config_dir = get_config_dir(argv)
    eas_client = get_client(config_dir)

    print("Press Ctrl+C to exit")
    try:
        result = await eas_client.async_get_transformer_tap_settings("test", feeder=None, transformer_mrid=None)
        pprint.pprint(result)
    except Exception as e:
        print(e)

    await eas_client.aclose()


if __name__ == "__main__":
    asyncio.run(print_loop(sys.argv))
