import asyncio
import sys
import pprint

from utils import get_client, get_config_dir
from zepben.eas import Query

"""
Get the transformer tap settings generated by a calibration run.

Use the name you provided in run_calibration.py
"""

CALIBRATION_NAME = "<CALIBRATION NAME>"  # Name the calibration run to fetch calibration sets for


async def print_loop(argv):
    config_dir = get_config_dir(argv)
    eas_client = get_client(config_dir)

    print("Press Ctrl+C to exit")
    try:
        result = await eas_client.query(Query.get_transformer_tap_settings(CALIBRATION_NAME))
        pprint.pprint(result)
    except Exception as e:
        print(e)

    await eas_client.close()


if __name__ == "__main__":
    asyncio.run(print_loop(sys.argv))
